gestao_contratos/core/urls.py
from django.urls import path

from gestao_contratos.core.views import home, atleta_cadastrar, LoginUser, LogoutUser

app_name = "core"

urlpatterns = [
    path("", home, name="home"),
    path("formulario/", atleta_cadastrar, name="formulario"),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout-user/", LogoutUser.as_view(), name="logout"),
]

gestao_contratos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gestao_contratos.core.urls")),
]

gestao_contratos/core/models.py
from django.db import models

from gestao_contratos.core.validators import name_validator, cpf_validator


class Athlete(models.Model):
    name = models.CharField(verbose_name='nome', max_length=40, validators=[name_validator])
    email = models.EmailField(verbose_name='e-mail')
    cpf = models.CharField(verbose_name='cpf', max_length=14, unique=True, validators=[cpf_validator])
    rg = models.CharField(verbose_name='rg', max_length=14)

    class Meta:
        verbose_name = 'atleta'
        verbose_name_plural = 'atletas'

    def __str__(self):
        return self.name


class Address(models.Model):
    cep = models.CharField(max_length=30)
    country = models.CharField(verbose_name='país', max_length=30)
    state = models.CharField(verbose_name='estado',  max_length=30)
    city = models.CharField(verbose_name='cidade', max_length=30)
    street = models.CharField(verbose_name='logradouro', max_length=30)
    number = models.CharField(verbose_name='número', max_length=10)
    complement = models.CharField(verbose_name='complemento', max_length=10, blank=True)
    athlete = models.ForeignKey('Athlete', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'endereço'
        verbose_name_plural = 'endereços'

    def __str__(self):
        return self.cep

gestao_contratos/core/forms.py
from django import forms

from gestao_contratos.core.models import Athlete


class AthleteForm(forms.ModelForm):
    class Meta:
        model = Athlete
        fields = ['name', 'email', 'cpf', 'rg']

gestao_contratos/core/views.py
from django.shortcuts import render

from django.contrib.auth.views import LoginView, LogoutView


def home(request):
    return render(request, "core/home.html")


def atleta_cadastrar(request):
    return render(request, "core/form_athlete.html")


class LoginUser(LoginView):
    template_name = 'core/login.html'


class LogoutUser(LogoutView):
    template_name = 'core/home.html'

gestao_contratos/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html class="h-100">
<head>
    <title>{% block title %} Gestão de Contrato de Atletas {% endblock title %}</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Gestão de Contratos de Atletas">
    <meta name="author" content="Rodrigo Delfino de Carvalho">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Favicon -->

    <!-- Bootstratp 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- Navbar cover css -->
    <link href="{% static 'core/cover.css' %}" rel="stylesheet">

    {% block style %}
    {% endblock style %}
</head>

<body>

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

{% include 'core/scripts.html' only %}

</body>
</html>

gestao_contratos/core/templates/core/form_athlete.html
{% extends 'core/base.html' %}


{% block content %}
{% include 'core/navbar.html' only %}
<body class="bg-dark">

<div class="container text-light pt-5">
  <main>
    <div class="py-5 text-center">
      <h2>Formulário de cadastro de atleta</h2>
    </div>

    <div class="row justify-content-center">

      <div class="col-md-7 col-lg-8">
        <form class="" >
          <div class="row g-3">

            <div class="col-sm-8">
              <label for="full_name" class="form-label">Nome completo</label>
              <input type="text" class="form-control" id="full_name" placeholder="João José da Silva" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-4">
              <label for="phone" class="form-label">Telefone</label>
              <input type="text" class="form-control" id="phone" placeholder="(11)91234-5678" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="cpf" class="form-label">Cpf</label>
              <input type="text" class="form-control" id="cpf" placeholder="123.456.789-00" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="rg" class="form-label">RG</label>
              <input type="text" class="form-control" id="rg" placeholder="12.456.456-78" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Opcional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="seu-email@examplo.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-3">
              <label for="zip" class="form-label">Cep</label>
              <input type="text" class="form-control" id="zip" placeholder="08123-000" required>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
            <div class="col-5">
              <label for="country" class="form-label">País</label>
              <select class="form-select" id="country" required>
                <option value="">Selecione...</option>
                <option>Brasil</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-4">
              <label for="state" class="form-label">Estado</label>
              <select class="form-select" id="state" required>
                <option value="">Selecione...</option>
                <option>São Paulo</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Endereço</label>
              <input type="text" class="form-control" id="address" placeholder="Av Cívica, 457 Centro, Mogi das Cruzes" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

          </div>
          <hr class="my-4">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Salvar dados</button>
        </form>
      </div>
    </div>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy;2021 Secretaria de Esporte e Lazer</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacidade</a></li>
      <li class="list-inline-item"><a href="#">Termos</a></li>
      <li class="list-inline-item"><a href="#">Suporte</a></li>
    </ul>
  </footer>
</div>

</body>
{% endblock content %}

gestao_contratos/core/templates/core/formulario.html
{% extends 'core/base.html' %}


{% block content %}
{% include 'core/navbar.html' only %}
<body class="bg-dark">

<div class="container text-light pt-5">
  <main>
    <div class="py-5 text-center">
      <h2>Formulário de cadastro de atleta</h2>
    </div>

    <div class="row">
      <div class="col-md-5 col-lg-4 order-md-last">
        <form class="">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <label class="">Dados financeiros</label>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div class="col-sm-12">
                <label for="salary" class="form-label">Salário</label>
                <input type="text" class="form-control" id="salary" placeholder="R$ 100,00" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div class="col-sm-12">
                <label for="fraction" class="form-label">Parcelas</label>
                <select class="form-select" id="fraction" required>
                  <option value="">Selecione...</option>
                  <option>1x</option>
                  <option>5x</option>
                  <option>12x</option>
                </select>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
            </li>
          </ul>
          <div class="py-2">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Salvar dados</button>
          </div>
        </form>
      </div>

      <div class="col-md-7 col-lg-8">
        <form class="needs-validation" novalidate>
          <div class="row g-3">

            <div class="col-sm-8">
              <label for="full_name" class="form-label">Nome completo</label>
              <input type="text" class="form-control" id="full_name" placeholder="João José da Silva" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

              <div class="col-sm-4">
              <label for="phone" class="form-label">Telefone</label>
              <input type="text" class="form-control" id="phone" placeholder="(11)91234-5678" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="cpf" class="form-label">Cpf</label>
              <input type="text" class="form-control" id="cpf" placeholder="123.456.789-00" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

              <div class="col-sm-6">
              <label for="rg" class="form-label">RG</label>
              <input type="text" class="form-control" id="rg" placeholder="12.456.456-78" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Opcional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="seu-email@examplo.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Endereço</label>
              <input type="text" class="form-control" id="address" placeholder="Av Cívica, 457 Centro, Mogi das Cruzes" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">País</label>
              <select class="form-select" id="country" required>
                <option value="">Selecione...</option>
                <option>Brasil</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">Estado</label>
              <select class="form-select" id="state" required>
                <option value="">Selecione...</option>
                <option>São Paulo</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Cep</label>
              <input type="text" class="form-control" id="zip" placeholder="08123-000" required>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>
          <hr class="my-4">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Salvar dados</button>
        </form>
      </div>
    </div>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy;2021 Secretaria de Esporte e Lazer</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacidade</a></li>
      <li class="list-inline-item"><a href="#">Termos</a></li>
      <li class="list-inline-item"><a href="#">Suporte</a></li>
    </ul>
  </footer>
</div>

</body>
{% endblock content %}

gestao_contratos/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
<body class="d-flex h-100 text-center text-white bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

    {% include 'core/navbar.html' %}


    <main class="px-3">
        <h1>Representante de equipe.</h1>
        <p class="lead">Este é o novo formulário para preenchimento com os dados dos seus atletas.
            Com base nessas respostas serão formalizados os contratos.</p>
        <p class="lead">
            <a href="{% url 'core:formulario' %}" class="btn btn-lg btn-secondary fw-bold border-white bg-white text-dark">Preencher formulário</a>
        </p>
    </main>

    <footer class="mt-auto text-white-50">
        <p>Created by <a href="#" class="text-white">Rodrigo Delfino de Carvalho</a>.</p>
    </footer>
</div>
</body>
{% endblock content %}

gestao_contratos/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block style %}
<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      html,
body {
  height: 100%;
}

body {
  display: flex;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

   </style>
{% endblock style %}

{% block content %}
<main class="form-signin">
  <form action="{% url 'core:login' %}" method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Efetuar login</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="username" name="username" placeholder="name2021">
      <label for="username">Usuário</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      <label for="password">Senha</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Lembrar-me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
    <p class="mt-5 mb-3 text-muted">2021</p>
  </form>
</main>
{% endblock content %}

gestao_contratos/core/templates/core/navbar.html
<header class="mb-auto">
    <div class="container">
        <div>
            <a href="{% url 'core:home' %}" class="text-light nav-link"><h3 class="float-md-start mb-0">Gestão de Contratos</h3></a>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                {% if user.is_authenticated %}
                    <p class="nav-link">Olá {{ user.username }}</p>
                    <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">Administrativo </a>
                    <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'core:login' %}">Login</a>
                {% endif %}
            </nav>
        </div>
    </div>
</header>

gestao_contratos/core/templates/core/scripts.html
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>